sudo: true
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - cppcheck
before_install:
  - python --version
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- sudo pip install gdown
- ./instal.sh
script:
  - make

