sudo: true
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - cppcheck
before_install:
  - python --version
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- sudo pip install gdown
- ./instal.sh
script:
  - cd ./software/tests/math/cos
  - make clean
  - make test
  - cppcheck test.c > cppcheck.log
  - gcov hf_riscv_sim.c >gcov.log
  - gprof ./hf_riscv_sim gmon.out >gprof.log
  - head cppcheck.log -n 200
  - head gcov.log -n 200
  - head gprof.log -n 200
  
  - cd ..
  - cd sin
  - make clean
  - make test
  - cppcheck test.c > cppcheck.log
  - gcov hf_riscv_sim.c >gcov.log
  - gprof ./hf_riscv_sim gmon.out >gprof.log
  - head cppcheck.log -n 200
  - head gcov.log -n 200
  - head gprof.log -n 200
  
  - cd ../..
  - cd ./libc/memcpy
  - make clean
  - make test
  - cppcheck test.c > cppcheck.log
  - gcov hf_riscv_sim.c >gcov.log
  - gprof ./hf_riscv_sim gmon.out >gprof.log
  - head cppcheck.log -n 200
  - head gcov.log -n 200
  - head gprof.log -n 200
  
  - cd ..
  - cd strcat
  - make clean
  - make test
  - cppcheck test.c > cppcheck.log
  - gcov hf_riscv_sim.c >gcov.log
  - gprof ./hf_riscv_sim gmon.out >gprof.log
  - head cppcheck.log -n 200
  - head gcov.log -n 200
  - head gprof.log -n 200
  
  - cd ../..
  - cd fixed/fix_exp
  - make clean
  - make test
  - cppcheck test.c > cppcheck.log
  - gcov hf_riscv_sim.c >gcov.log
  - gprof ./hf_riscv_sim gmon.out >gprof.log
  - head cppcheck.log -n 200
  - head gcov.log -n 200
  - head gprof.log -n 200
  
  - cd ..
  - cd ./fix_sqrt
  - make clean
  - make test
  - cppcheck test.c > cppcheck.log
  - gcov hf_riscv_sim.c >gcov.log
  - gprof ./hf_riscv_sim gmon.out >gprof.log
  - head cppcheck.log -n 200
  - head gcov.log -n 200
  - head gprof.log -n 200
  
  - cd ../..
  - cd ./matrix/copy
  - make clean
  - make test
  - cppcheck test.c > cppcheck.log
  - gcov hf_riscv_sim.c >gcov.log
  - gprof ./hf_riscv_sim gmon.out >gprof.log
  - head cppcheck.log -n 200
  - head gcov.log -n 200
  - head gprof.log -n 200
  
  - cd ..
  - cd transposed
  - make clean
  - make test
  - cppcheck test.c > cppcheck.log
  - gcov hf_riscv_sim.c >gcov.log
  - gprof ./hf_riscv_sim gmon.out >gprof.log
  - head cppcheck.log -n 200
  - head gcov.log -n 200
  - head gprof.log -n 200

